# Generated by Django 4.2 on 2023-04-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'completed'), (3, 'postponed'), (4, 'cancelled')], default=1, null=True),
        ),
    ]
